### ISSUE TITLE
Future of this plugin

### ISSUE THREAD

**Issue by evant** [JCAndKSolutions/android-unit-test#105] opened 2015-02-09 21:53 UTC
With google releasing [proper support](http://tools.android.com/tech-docs/unit-testing-support) for this, I'm wondering what you future plans were. I was planning on deprecating the IDE plugin, but I don't want to cause any undue burden because of that.

**Comment by SuperJugy** [comment] 2015-02-09 21:57
I was thinking of deprecating this plugin as well.

**Comment by nenick** [comment] 2015-02-11 06:54
You both created awesome plugins, thank you! Now robolectric works great with native unit test support  https://github.com/nenick/AndroidStudioAndRobolectric

**Comment by SuperJugy** [comment] 2015-02-11 15:26
Thanks for your kind words. I will wait until the release candidate is released as a stable version to deprecate.

**Comment by pawelByszewski** [comment] 2015-03-18 08:31
Guys, I have tried to use native support in my already existing project. In sample, small project everything works great but in pretty complicated project with few modules and few flavors it fails:(
So please do not deprecated this plugin :)

**Comment by Toppole6** [comment] 2023-05-23 17:27
> With google releasing [proper support](http://tools.android.com/tech-docs/unit-testing-support) for this, I'm wondering what you future plans were. I was planning on deprecating the IDE plugin, but I don't want to cause 

> @
Duplicate of #any undue burden because of that.

**Comment by JurgenCruz** [comment] 2023-05-23 18:07
This plug-in has been deprecated since 2015. I will close this issue now.

**Closed by JurgenCruz** 2023-05-23 18:07 UTC
