### ISSUE TITLE
ClassNotFoundException when tests are run immediately after clean

### ISSUE THREAD

**Issue by nextdoor-engineer** [JCAndKSolutions/android-unit-test#94] opened 2015-01-03 01:18 UTC
Versions:
* android-unit-test 2.1.1
* Android build tools 21.1.2
* Gradle 2.2.1
* Robolectric 2.3

Repro:
1. `./gradlew clean`
2. `./gradlew test`

Expected: All tests pass

Actual: The first time `./gradlew test` is run, the following output appears:

    ➜  nextdoor git:(master) ./gradlew test 
    [buildinfo] Properties file path was not found! (Relevant only for builds running on a CI Server)
    :preBuild
    :preDebugBuild
    :checkDebugManifest
    :preNightlyBuild
    :prePlaystoreBuild
    :preRcBuild
    :preReleaseBuild
    :preStagingBuild
    :prepareComActionbarsherlockActionbarsherlock440Library
    :prepareComAndroidSupportCardviewV72100Library
    :prepareComAndroidSupportMultidex100Library
    :prepareComAndroidSupportSupportV42103Library
    :prepareComGithubChrisbanesActionbarpulltorefreshExtraAbs07Library
    :prepareComGithubChrisbanesActionbarpulltorefreshLibrary07Library
    :prepareComGoogleAndroidGmsPlayServices6587Library
    :prepareComInstabugLibraryInstabugabs123Library
    :prepareComInstabugLibraryInstabugcore123Library
    :prepareFrAvianeyFacebookAndroidApi3180Library
    :prepareDebugDependencies
    :compileDebugAidl
    :compileDebugRenderscript
    :generateDebugBuildConfig
    :generateDebugAssets UP-TO-DATE
    :mergeDebugAssets
    :generateDebugResValues UP-TO-DATE
    :generateDebugResources
    :mergeDebugResources
    /Users/wesley/src/mobile/android/nextdoor/src/main/res/drawable-hdpi/profile_bio_paragraph.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

[SNIP: a whole lot of warnings like the ones above and below]

    /Users/wesley/src/mobile/android/nextdoor/src/main/res/drawable-xxxhdpi/profile_camera_white.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
    :processDebugManifest
    :processDebugResources
    :generateDebugSources
    :compileDebugJava
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    :compileTestDebugJava
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    :processTestDebugResources
    :testDebugClasses
    :testDebug
    objc[85705]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
    Jan  2 17:07:52 wesley-nextdoor.local java[85705] <Error>: The function ‘CGContextErase’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.

    com.nextdoor.activity.DetailNewsFeedActivityTest > testLoadDetailNewsFeedListFragment FAILED
        org.fest.reflect.exception.ReflectionError at DetailNewsFeedActivityTest.java:53
            Caused by: java.lang.NoClassDefFoundError at DetailNewsFeedActivityTest.java:53
                Caused by: java.lang.ClassNotFoundException at DetailNewsFeedActivityTest.java:53
        java.lang.NullPointerException at DetailNewsFeedActivityTest.java:60

    com.nextdoor.activity.MainFeedActivityTest > testLoadEvents FAILED
        org.fest.reflect.exception.ReflectionError at MainFeedActivityTest.java:59
            Caused by: java.lang.NoClassDefFoundError at MainFeedActivityTest.java:59
                Caused by: java.lang.ClassNotFoundException at MainFeedActivityTest.java:59
        java.lang.NullPointerException at MainFeedActivityTest.java:66

    com.nextdoor.activity.MainFeedActivityTest > testLoadGroups FAILED
        org.fest.reflect.exception.ReflectionError at MainFeedActivityTest.java:59
            Caused by: java.lang.NoClassDefFoundError at MainFeedActivityTest.java:59
                Caused by: java.lang.ClassNotFoundException at MainFeedActivityTest.java:59
        java.lang.NullPointerException at MainFeedActivityTest.java:66

    com.nextdoor.activity.MainFeedActivityTest > testLoadNewsFeed FAILED
        org.fest.reflect.exception.ReflectionError at MainFeedActivityTest.java:59
            Caused by: java.lang.NoClassDefFoundError at MainFeedActivityTest.java:59
                Caused by: java.lang.ClassNotFoundException at MainFeedActivityTest.java:59
        java.lang.NullPointerException at MainFeedActivityTest.java:66

    com.nextdoor.activity.MainFeedActivityTest > testLoadBookmarks FAILED
        org.fest.reflect.exception.ReflectionError at MainFeedActivityTest.java:59
            Caused by: java.lang.NoClassDefFoundError at MainFeedActivityTest.java:59
                Caused by: java.lang.ClassNotFoundException at MainFeedActivityTest.java:59
        java.lang.NullPointerException at MainFeedActivityTest.java:66

    com.nextdoor.activity.MainFeedActivityTest > testLoadNeighborhoodDirectory FAILED
        org.fest.reflect.exception.ReflectionError at MainFeedActivityTest.java:59
            Caused by: java.lang.NoClassDefFoundError at MainFeedActivityTest.java:59
                Caused by: java.lang.ClassNotFoundException at MainFeedActivityTest.java:59
        java.lang.NullPointerException at MainFeedActivityTest.java:66

    com.nextdoor.activity.MainFeedActivityTest > testDefaultMainfeedActivityCreation FAILED
        org.fest.reflect.exception.ReflectionError at MainFeedActivityTest.java:59
            Caused by: java.lang.NoClassDefFoundError at MainFeedActivityTest.java:59
                Caused by: java.lang.ClassNotFoundException at MainFeedActivityTest.java:59
        java.lang.NullPointerException at MainFeedActivityTest.java:66

    com.nextdoor.activity.MainFeedActivityTest > testLoadInbox FAILED
        org.fest.reflect.exception.ReflectionError at MainFeedActivityTest.java:59
            Caused by: java.lang.NoClassDefFoundError at MainFeedActivityTest.java:59
                Caused by: java.lang.ClassNotFoundException at MainFeedActivityTest.java:59
        java.lang.NullPointerException at MainFeedActivityTest.java:66

    com.nextdoor.activity.MainFeedActivityTest > testLoadNeighborhoodMap FAILED
        org.fest.reflect.exception.ReflectionError at MainFeedActivityTest.java:59
            Caused by: java.lang.NoClassDefFoundError at MainFeedActivityTest.java:59
                Caused by: java.lang.ClassNotFoundException at MainFeedActivityTest.java:59
        java.lang.NullPointerException at MainFeedActivityTest.java:66

    com.nextdoor.fragment.NewsFeedListFragmentTest > inviteBannerTest FAILED
        org.fest.reflect.exception.ReflectionError at NewsFeedListFragmentTest.java:92
            Caused by: java.lang.NoClassDefFoundError at NewsFeedListFragmentTest.java:92
                Caused by: java.lang.ClassNotFoundException at NewsFeedListFragmentTest.java:92
        java.lang.NullPointerException at NewsFeedListFragmentTest.java:81

    com.nextdoor.fragment.NewsFeedListFragmentTest > testNearbyCustomizeTextViewClick FAILED
        org.fest.reflect.exception.ReflectionError at NewsFeedListFragmentTest.java:92
            Caused by: java.lang.NoClassDefFoundError at NewsFeedListFragmentTest.java:92
                Caused by: java.lang.ClassNotFoundException at NewsFeedListFragmentTest.java:92
        java.lang.NullPointerException at NewsFeedListFragmentTest.java:81

    com.nextdoor.fragment.NewsFeedListFragmentTest > shouldHaveNewsfeedStories FAILED
        org.fest.reflect.exception.ReflectionError at NewsFeedListFragmentTest.java:92
            Caused by: java.lang.NoClassDefFoundError at NewsFeedListFragmentTest.java:92
                Caused by: java.lang.ClassNotFoundException at NewsFeedListFragmentTest.java:92
        java.lang.NullPointerException at NewsFeedListFragmentTest.java:81

    com.nextdoor.fragment.NewsFeedListFragmentTest > shouldNotHaveNewsfeedStories FAILED
        org.fest.reflect.exception.ReflectionError at NewsFeedListFragmentTest.java:92
            Caused by: java.lang.NoClassDefFoundError at NewsFeedListFragmentTest.java:92
                Caused by: java.lang.ClassNotFoundException at NewsFeedListFragmentTest.java:92
        java.lang.NullPointerException at NewsFeedListFragmentTest.java:81

    com.nextdoor.fragment.NewsFeedListFragmentTest > refreshNewsfeedStoriesAfterError FAILED
        org.fest.reflect.exception.ReflectionError at NewsFeedListFragmentTest.java:92
            Caused by: java.lang.NoClassDefFoundError at NewsFeedListFragmentTest.java:92
                Caused by: java.lang.ClassNotFoundException at NewsFeedListFragmentTest.java:92
        java.lang.NullPointerException at NewsFeedListFragmentTest.java:81

    com.nextdoor.fragment.NuxSignInFragmentTest > shouldHaveUsernameAndPasswordFields FAILED
        java.lang.NoClassDefFoundError at NuxSignInFragmentTest.java:48
            Caused by: java.lang.ClassNotFoundException at NuxSignInFragmentTest.java:48

    com.nextdoor.fragment.NuxSignInFragmentTest > shouldHaveLoginButton FAILED
        java.lang.NoClassDefFoundError at NuxSignInFragmentTest.java:48

    359 tests completed, 16 failed
    :testDebug FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':testDebug'.
    > There were failing tests. See the report at: file:///Users/wesley/src/mobile/android/nextdoor/build/test-report/debug/index.html

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 54.941 secs

Notes:
* This only occurs with a separate `./gradlew clean` and `./gradlew test`. If `./gradlew test` has been run before, `./gradlew clean test` will succeed.

**Comment by SuperJugy** [comment] 2015-01-05 00:22
Are you using some kind of code generation? because the example project in the repo when run on Travis it is always a clean build and it works just fine. also, please notice that only 16 of your tests failed. what class is it not finding? where is this class coming from?

I'm guessing you are adding extra tasks after the tests that generate other classes that are then seen when it is not a clean build. if that is the case you just have to use `dependsOn` to fix the task order so the class is generated before the tests.

**Comment by SuperJugy** [comment] 2015-01-16 15:47
Hey, have you found a solution for this? otherwise I will close it since I can't reproduce.

**Comment by mttmllns** [comment] 2015-01-16 22:04
I'm getting the same issue but it's all of our tests failing. We do use dagger and I do have a custom copy task that I will start troubleshooting.  After previous runs if I do `gradlew clean test` it runs fine but `gradlew clean` followed by `gradlew test` blows up.

I only found this because our Jenkins CI does a `git clean -fdx` before each build.  I'll report back with any solutions I find.

**Comment by SuperJugy** [comment] 2015-01-16 22:25
If you are using dagger then you have to make sure to only set the right task dependencies and also to include the generated code in the sourcepath of the tests. In any case, This plugin doesn't support custom plugins that add autogenerated code. If you have autogenerated code, its your responsibility to configure the plugin to pickit up and to have the correct order of tasks.

**Comment by mttmllns** [comment] 2015-01-16 22:29
Yep!  Feel free to close the issue as it's definitely something weird we're doing.  I'll follow up with findings for Googleable posterity.  Thanks for your input.

**Closed** 2015-01-16 22:30 UTC
Labels: invalid

**Comment by mttmllns** [comment] 2015-01-18 01:32
Well I ruled out the copy tasks we're doing.  Trimmed our script down to the bare essentials and tests are still failing on an truly-clean build.

A few failures are on DrawerLayoutImpl:

```
java.lang.NoClassDefFoundError: android/support/v4/widget/DrawerLayoutImpl
Caused by: java.lang.ClassNotFoundException: android.support.v4.widget.DrawerLayoutImpl
```

and the rest fail with a `NullPointerException` on our `getApplicationGraph()` call.  This is hard to debug as the clean issue isn't reproducible in Android Studio. I threw some logs in instead and finally tracked it down to our `TestMainApplication` class (trimmed down):

```java
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.mockito.Mockito;
import org.mockito.invocation.InvocationOnMock;
import org.mockito.stubbing.Answer;
import org.robolectric.Robolectric.Reflection;
import org.robolectric.TestLifecycleApplication;

// ...

import dagger.Module;
import dagger.ObjectGraph;
import dagger.Provides;

public class TestMainApplication extends MainApplication implements TestLifecycleApplication {

	private ObjectGraph _injectionGraph = null;

	public ActivityLifecycleService mockActivityLifecycleService = null;
	// ...

	@Module(
			includes = ApplicationModule.class,
			injects = {
					// ...
			},
			overrides = true,
			library = true)
	public class TestModule {

		@Provides
		ActivityLifecycleService provideActivityLifecycleService() {
			return mockActivityLifecycleService;
		}

		// ...

		// Not mocked
		@Provides
		ObjectGraph provideObjectGraph() {
			return _injectionGraph;
		}
	}

	public TestMainApplication() {
	}

	@Override
	public void onCreate() {
		System.out.println("INSIDE ONCREATE");

		super.onCreate();
	}

	@Override
	public void beforeTest(Method method) {
		System.out.println("INSIDE BEFORETEST");
	}

	@Override
	public void prepareTest(Object test) {
		System.out.println("INSIDE PREPARETEST");

		// reset all mocks on each test run.
		mockActivityLifecycleService = mock(ActivityLifecycleService.class);	
		// ...

		List<Object> modules = new ArrayList<Object>();
		modules.add(new TestModule());
		if (test instanceof ModuleProvider) {
			modules.add(((ModuleProvider) test).getModule());
		}

		_injectionGraph = ObjectGraph.create(modules.toArray());
		_injectionGraph.injectStatics();
	}

	@Override
	public void afterTest(Method method) {
		System.out.println("INSIDE AFTERTEST");
	}

	@Override
	public ObjectGraph getApplicationGraph() {
		return _injectionGraph;
	}
}
```

On a successful test run during **every test** I get all logs:

```
INSIDE ONCREATE
INSIDE BEFORETEST
DEBUG: Loading resources for com.adobe.dps.viewer from ././src/main/res...
INSIDE PREPARETEST
DEBUG: Loading resources for android from jar:/Users/mmullins/.m2/repository/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar!/res...
INSIDE AFTERTEST
``` 

but on the truly-clean test run I only get **one** set of logs for the very first test class only and `prepareTest`, which is instrumental in creating the objectgraph, is missing:

```
INSIDE ONCREATE
INSIDE BEFORETEST
DEBUG: Loading resources for com.adobe.dps.viewer from ././src/main/res...
INSIDE AFTERTEST
```

For every other test there are no logs at all. Seems to me this may indeed be an issue with this plugin, android's plugin, or gradle itself. Any thoughts @SuperJugy?  Let me know if you want any other logs.

Our simplified build.gradle for reference:

```gradle
apply plugin: 'com.android.application'

android {
	compileSdkVersion 19
	buildToolsVersion "21.1.2"

	defaultConfig {
		applicationId "com.adobe.dps.viewer"
		minSdkVersion 19
		targetSdkVersion 19
		versionCode 15
		versionName "33.0.0"
	}
}

apply plugin: 'android-unit-test'

androidUnitTest {
	testTasks {
		all {
			include '**/*Tests.class'
		}
	}
}

dependencies {
	// Include any local dependencies in the libs directory
	compile fileTree(dir: 'libs', include: ['*.jar'])

	compile 'com.android.support:support-v4:21.0.3'
	compile 'com.android.support:recyclerview-v7:21.0.2'
	compile 'com.squareup.dagger:dagger:1.2.2'
	provided 'com.squareup.dagger:dagger-compiler:1.2.2'
	compile 'com.google.guava:guava:16.0.1'
	compile 'com.j256.ormlite:ormlite-android:4.48'
	compile 'net.jcip:jcip-annotations:1.0'
	compile 'com.squareup.okhttp:okhttp:2.1.0'
	compile 'com.fasterxml.jackson.core:jackson-core:2.4.0'
	compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.1'
	compile 'com.github.bumptech.glide:glide:3.4.0'
	compile 'com.github.bumptech.glide:okhttp-integration:1.1.0'

	testCompile 'junit:junit:4.12'
	testCompile 'org.mockito:mockito-core:1.10.17'
	testCompile 'com.squareup:fest-android:1.0.3'
	testCompile 'org.robolectric:robolectric:2.4'
}
```

**Comment by mttmllns** [comment] 2015-01-18 02:10
Scratch that...red herring. I'll update with the new details.

**Comment by mttmllns** [comment] 2015-01-18 02:17
Seems like a lot of my problems are something to do with AppCompat not working with Robolectric 2.4.  See here: https://github.com/robolectric/robolectric/issues/1385

**Comment by SuperJugy** [comment] 2015-01-18 02:29
I see, good to know. Thanks.

**Comment by wesleym** [comment] 2015-01-19 00:21
Hi, I opened this issue. I haven't been able to rule out that this is a problem with our setup, so I'm happy to leave it closed until I can get a good repro case.

**Comment by DoronK** [comment] 2017-05-16 11:49
Commenting out testCoverageEnabled true did the trick for me. 
```
buildTypes { 
debug { 
// testCoverageEnabled true 
} 
}
```
